{% set name = "solarwindpy" %}
{% set version = "0.1.dev1034+gb4f715534.d20250819" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5e9f04a491ca1dfd2348bdd475ba468b05f6230b3b1b891ea34c70296e597de0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - numpy
    - scipy
    - pandas
    - numexpr
    - bottleneck
    - h5py
    - pyyaml
    - matplotlib
    - astropy
    - numba
    - tabulate

test:
  imports:
    - solarwindpy

about:
  home: https://github.com/blalterman/SolarWindPy
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: "Python package for solar wind data analysis."

extra:
  recipe-maintainers:
    - blalterman
