{% set name = "solarwindpy" %}
{% set version = "0.1.dev537+g7af580e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7,<4
    - pip
  run:
    - python >=3.7,<4
    - numpy
    - scipy
    - pandas
    - numexpr
    - bottleneck
    - h5py
    - pyyaml
    - matplotlib
    - datetime
    - astropy
    - numba
    - tabulate

test:
  imports:
    - solarwindpy

about:
  home: https://github.com/blalterman/SolarWindPy
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: Python package for solar wind data analysis.

extra:
  recipe-maintainers:
    - your-github-username
