{% set name = "solarwindpy" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/solarwindpy-{{ version }}.tar.gz
  sha256: de5a5ecaa745df45d8500ed5ed8208bda716950895c123a3508ccf6ad3b78d89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10,<4.0
    - setuptools >=61
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.10,<4.0
    - numpy
    - scipy
    - pandas
    - numexpr
    - bottleneck
    - h5py
    - pyyaml
    - matplotlib-base
    - astropy
    - numba
    - tabulate

test:
  imports:
    - solarwindpy
    - solarwindpy.core
    - solarwindpy.plotting
    - solarwindpy.fitfunctions
    - solarwindpy.instabilities
    - solarwindpy.solar_activity
    - solarwindpy.tools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/blalterman/SolarWindPy
  summary: Python package for solar wind data analysis.
  description: |
    SolarWindPy provides tools for analyzing in-situ solar wind measurements,
    including multi-species plasma analysis, magnetic field calculations,
    and plasma instability studies.
  dev_url: https://github.com/blalterman/SolarWindPy
  license: BSD-3-Clause
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - blalterman
