version: 1

formatters:
    detailed: 
        format: "%(asctime)s - %(name)s - %(filename)s - %(lineno)d - %(levelname)s - %(message)s"
    simple:
        format: "%(message)s\n"
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
    main:
        class: logging.FileHandler
        level: DEBUG
        formatter: detailed
        filename: main.log
    core:
        class: logging.FileHandler
        level: DEBUG
        formatter: detailed
        filename: solarwindpy/core.log
    plotting:
        class: logging.FileHandler
        level: DEBUG
        formatter: detailed
        filename: solarwindpy/plotting.log
    solar_activity:
        class: logging.FileHandler
        level: DEBUG
        formatter: detailed
        filename: solarwindpy/solar_activity.log
loggers:
    main:
        propagate: True
        level: DEBUG
        handlers: [console, main]
    solarwindpy:
        level: DEBUG
        propagate: True
        handlers: [console]
    solarwindpy.core:
        propagate: True
        handlers: [core]
    solarwindpy.plotting:
        propagate: True
        handlers: [plotting]
    solarwindpy.solar_activity:
        propagate: True
        handlers: [solar_activity]
