name: Performance Benchmark

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev pkg-config
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          # Install pytables separately with verbose output for debugging
          pip install --verbose tables
          pip install -r requirements-dev.txt
          pip install pytest-benchmark memory_profiler
          pip install -e .
      
      - name: Run benchmarks
        run: |
          mkdir -p benchmark-results
          pytest tests/ -v \
                 --benchmark-only \
                 --benchmark-json=benchmark-results/benchmark.json \
                 --benchmark-histogram=benchmark-results/histogram \
                 --benchmark-storage=benchmark-results/storage
        continue-on-error: true
      
      - name: Upload benchmark artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results-${{ github.run_id }}
          path: benchmark-results/
          retention-days: 90
      
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: benchmark-results/benchmark.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: false
          comment-on-alert: true
          alert-threshold: '150%'  # Alert if 50% slower
          fail-on-alert: false