name: Configure Branch Protection

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'master'
        type: choice
        options:
          - master
          - main
          - develop
      enforce_admins:
        description: 'Apply rules to administrators'
        required: false
        default: false
        type: boolean

jobs:
  protect-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure branch protection
        uses: benjefferies/branch-protection-bot@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.inputs.branch }}
          enforce_admins: ${{ github.event.inputs.enforce_admins }}
          required_status_checks: |
            CI (ubuntu-latest, 3.11)
            CI (ubuntu-latest, 3.8)
            Documentation / build
            Security Scan / security
          required_approving_review_count: 1
          dismiss_stale_reviews: true
          require_code_owner_reviews: false
          restrictions: ""  # No user/team restrictions