name: CI

on:
  push:
    branches: [master, update-2025]
  pull_request:
    branches: [master, update-2025]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install .
      - name: Lint code
        run: flake8
      - name: Lint docs
        run: doc8 README.rst docs CITATION.rst --ignore-path docs/source/solarwindpy.solar_activity.tests.rst
      - name: Run tests
        run: pytest -q
