name: Semantic Version Validation

on:
  push:
    tags:
      - '*'  # Validate all tags
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/semver-check.yml'
      - '.claude/hooks/validate-tags.sh'
  workflow_dispatch:  # Allow manual testing

jobs:
  validate-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tag validation
      
      - name: Make validate-tags.sh executable
        run: chmod +x .claude/hooks/validate-tags.sh
      
      - name: Validate semantic version tags
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Validating tag: $TAG"
          ./.claude/hooks/validate-tags.sh "$TAG"
          
      - name: Test validation hook
        if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Testing semantic version validation..."
          
          # Test valid tags
          echo "Testing valid release tags:"
          ./.claude/hooks/validate-tags.sh || exit 1
          echo "✅ Tag validation passed"